### ISSUE TITLE
Flex panics if insights api url is not resolved (DNS)

### ISSUE THREAD

**Issue by carlosroman** [newrelic/nri-flex#130]
```
time="2020-03-23T14:39:16+11:00" level=info msg="flex: completed processing configs" configs=89
time="2020-03-23T14:39:16+11:00" level=debug msg="posting 90 events to insights"
time="2020-03-23T14:39:16+11:00" level=debug msg="http: insights - bytes 12871 events 0"
time="2020-03-23T14:39:16+11:00" level=error msg="http: failed to send" error="Post https://insights-collector.newrelic.com/v1/accounts/2625115/events: dial tcp: lookup insights-collector.newrelic.com on 192.168.84.41:53: no such host"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd01163]
goroutine 1 [running]:
github.com/newrelic/nri-flex/internal/outputs.postRequest(0xc00003800d, 0x42, 0xc000036011, 0x25, 0xc000a88000, 0x1b1a5, 0x1c000, 0x0, 0x0)
    /home/travis/gopath/src/github.com/newrelic/nri-flex/internal/outputs/http.go:48 +0x7e3
github.com/newrelic/nri-flex/internal/outputs.SendBatchToInsights(0xc00018ac00, 0x5a, 0x80, 0x0, 0x0)
    /home/travis/gopath/src/github.com/newrelic/nri-flex/internal/outputs/insights.go:55 +0x20c
github.com/newrelic/nri-flex/internal/integration.RunFlex(0x0, 0xc0003c4e10, 0xf7c453)
    /home/travis/gopath/src/github.com/newrelic/nri-flex/internal/integration/integration.go:122 +0x3c6
main.main()
    /home/travis/gopath/src/github.com/newrelic/nri-flex/cmd/nri-flex/nri-flex.go:32 +0x2c4```

**Comment by carlosroman** [comment]
This was fixed in `v1.1.1`
